name: Slack Notification

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: npm start

      - name: Fetch API status
        run: |
          curl -i http://localhost:3000/api/status

      - name: Notify Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          retries=0
          while [ $retries -lt 5 ]; do
            node notifySlack.js
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              break
            else
              sleep_seconds=$((2 ** retries))
              echo "Retrying in $sleep_seconds seconds..."
              sleep $sleep_seconds
              retries=$((retries + 1))
            fi
          done
